# Generated by Django 4.2.6 on 2023-11-06 15:10

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MNC', 'MNC'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MEC', 'MEC'), ('CER', 'CER'), ('CHE', 'CHE'), ('CIV', 'CIV'), ('MET', 'MET'), ('MIN', 'MIN'), ('PHE', 'PHE'), ('APD', 'APD')], max_length=50),
        ),
    ]
