# Generated by Django 4.2.6 on 2023-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_sem_courses_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
