# Generated by Django 4.2.6 on 2023-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(default='profile_pics/default_student.png', upload_to='profile_pics'),
        ),
    ]
